export const DATABASE_CONNECTION = 'mongodb://localhost/shopDEV'
export const SHOP_MODEL = 'shop'
export const KEY_MODEL = 'key'
export const APIKEY_MODEL = 'apikey'
export const PRODUCT_MODEL = 'product'
export const CART_MODEL = 'cart'
export const NOTIFICATION_MODEL = 'notification'
export const USER_MODEL = 'user'